[model]
name = "MSGNet"

[model.params]
enc_in = 7
d_model = 128
d_ff = 256
e_layers = 2
n_heads = 8
top_k = 5
dropout = 0.1
conv_channel = 32
skip_channel = 32
gcn_depth = 2
propalpha = 0.3
node_dim = 10
individual = false
embed = "timeF"
freq = "h"
