[model]
name = "PatchTST"

[model.params]
enc_in = 7
patch_len = 16
stride = 8
padding_patch = "end"
e_layers = 3
d_model = 512
n_heads = 8
d_ff = 2048
activation = "gelu"
norm = "BatchNorm"
attn_dropout = 0.0
ffn_dropout = 0.0
res_dropout = 0.0
proj_dropout = 0.0
head_dropout = 0.0
pre_norm = false
pe = "zeros"
learn_pe = false
head_type = "flatten"
individual = false
revin = true
affine = false
subtract_last = false
