[model]
name = "TimeEmb"

[model.params]
enc_in = 7
d_model = 512
use_revin = true
use_hour_index = true
use_day_index = false
scale = 0.02
hour_length = 24
day_length = 7
rec_lambda = 0.0
auxi_lambda = 1.0
auxi_loss = "MAE"
auxi_mode = "fft"
auxi_type = "complex"
module_first = true
leg_degree = 2
add_noise = false
