[model]
name = "TimePerceiver"

[model.params]
enc_in = 7
d_model = 32
n_heads = 2
d_ff = 256
patch_len = 16
dropout = 0.1
num_latents = 8
latent_dim = 128
latent_d_ff = 256
num_latent_blocks = 1
use_latent = true
query_share = true
