[model]
name = "TimeMixer"

[model.params]
enc_in = 7
c_out = 7
freq = "h"
embed = "timeF"
e_layers = 2
d_model = 512
d_ff = 2048
down_sampling_window = 1
down_sampling_layers = 0
down_sampling_method = ""
channel_independence = false
moving_avg = 25
top_k = 5
dropout = 0.0
use_norm = true
decomp_method = "moving_avg"
